network:
  version: 2
  ethernets:
    enp0s8:
      addresses: 
        - 10.0.3.3/24
      routes:
        - to: default
          via: 10.0.3.1
      dhcp4: false
      nameservers:
        addresses:
          - 8.8.8.8