
- name: Install ca-certificates and curl
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    update_cache: True

- name:  Create directory for Docker key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Set permissions for Docker key
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Set DPKG architecture
  set_fact:
    dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

- name: Add Docker repository
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    create: yes
    line: |-
      deb [arch={{ dpkg_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

- name: Update package lists after adding repository and Install Docker package
  ansible.builtin.apt:
    name: docker-ce
    update_cache: True

- name:  Configure the Docker daemon VM insecure registry
  ansible.builtin.template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"
    mode: '0777'
  notify: Restart Docker service