- name: Install m8s
  community.general.snap:
    classic: true
    channel: 1.28/stable
    name:
      - microk8s
  register: install_result

- name: Wait for m8s to be ready
  include_tasks: wait.yml
  when: "'snaps_installed' in install_result"

- name: Add user vagrant to the microk8s group
  ansible.builtin.user:
    name: vagrant
    groups: microk8s
    append: yes
  when: "'snaps_installed' in install_result"

  