- name: Install m8s
  community.general.snap:
    classic: true
    channel: 1.28/stable
    name:
      - microk8s

- name: Wait for m8s to be ready
  ansible.builtin.command: microk8s.status --wait-ready
  register: status_result
  changed_when: false
  failed_when: status_result.stdout_lines[0] != "microk8s is running"

- name: Add user vagrant to the microk8s group
  ansible.builtin.user:
    name: vagrant
    groups: microk8s
    append: yes

  